GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/KSPCommunityFixes.csproj, KSPCommunityFixes/QoL/HidePartUpgradeExtendedInfo.cs
Part Upgrades hijack the existing part tooltip system, but (either because I was dumb at the time, or because it atrophied later, can't remember at this point) when you right-click to get them to stick (and so you can purchase them), the extended info tab of the base AvailablePart/PartPrefab used for the icon gets displayed. Ugh.
This simple fix will prevent it from displaying.
=> New QoL Feature: allow hide extended info of PartUpgrade parttooltips

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/BugFixes/DeltaVHideWhenDisabled.cs, KSPCommunityFixes/KSPCommunityFixes.csproj
Otherwise it's just showing a bunch of "0m/s" and empty UI windows, which looks broken.
Annoyingly there's a little empty gray area where the total dV display was on the staging UI, but I'm not seeing an obvious way to remove it or shrink the background, so eh. Better than a constant display of "0m/s" there at least.
=> Hide delta V UI when the stock delta V app/calculations are disabled.

KSPCommunityFixes/QoL/HidePartUpgradeExtendedInfo.cs
Sorry, my first fix was bugged. Wouldn't show extended info sometimes for regular parts.
=> Fix upgrade parttooltip info hiding

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/KSPCommunityFixes.csproj, KSPCommunityFixes/QoL/ShowContractFinishDates.cs
Small QoL feature: right now KSP shows accepted/offered/deadline/etc dates for offered and active contracts, but shows *no date at all* for archived contracts. This patch makes it so that archived contracts show the date they were accepted and the date they completed/failed/etc.
Defaults to false, which I think is correct? I mean, *I* would always play with it turned on, but I'm not 100% comfortable making that call be the default.
=> For archived contracts, show accepted/finished dates.

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/KSPCommunityFixes.csproj, KSPCommunityFixes/Performance/ProgressTrackingSpeedBoost.cs
KSP's stock ProgressTracking evaluates every progress node for every vessel in the universe.
There are ~19 progress nodes per celestial body, and this can get extremely expensive for mods with a
large number of bodies or saves with a large number of vessels.
This tweak only evaluates the currently active vessel and removes the per-body checks which don't
have any effect, at least in the stock game.
=> Fix #55: Add ProgressTrackingSpeedBoost

KSPCommunityFixes/Modding/PersistentIConfigNode.cs
The writing of Persistent IConfigNode objects was broken in some cases because the check was after the IsArrayType check, etc. This fixes it by bringing the check up to the top, which is correct (if the object is IConfigNode, then that should be used in preference to anything else.)
=> Fix ordering when writing Persistent IConfigNode

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/BugFixes/StrategyDuration.cs, KSPCommunityFixes/KSPCommunityFixes.csproj
Stock has broken support for min/max durations for strategies. This fixes:
* LongestDuration to actually use longestDuration fields
* Least and Longest Duration getters to use the duration properties, not the fields (which are never set)
* CanBeActivated to not have its inequality flipped when comparing LeastDuration + DateActivated vs UT.
Since the property patches are 75% new code it didn't seem worth trying to transpile them from near-scratch. If you want to you can, it involves replacing the ldflds with calls to the properties.
=> Fix Strategy Duration handling

KSPCommunityFixes/BugFixes/UpgradeBugs.cs
This is true only for PartModules that are added via code, and only on the prefab itself it appears.
The symptom only occurs on parts with upgrades but that have code-added modules, and only when the substitute part fix is disabled. (I tested against regular KSP, and against RP-1 with both patches enabled, but missed this particular set of cases. Thankfully a user on the RO discord encountered it and I was able to diagnose.)
=> Fix a bug in the UpgradesBugs patch where the upgrades field could be null

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/KSPCommunityFixes.csproj, KSPCommunityFixes/Performance/FewerSaves.cs
On despawn of AC/Admin/MC/RnD, and on delete vessel in TS. Written by @siimav, KSPCF'd by me.
=> Performance optimization: support eliminating some extraneous saving by KSP

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/BugFixes/MapSOWrapping.cs, KSPCommunityFixes/KSPCommunityFixes.csproj
Fixes issues with biomes crossing the poles (South pole biome at north pole and vice versa). Fixes "polar spikes" in the terrain for 8-bit heightmaps (16-bit already fixed in RSS).
=> Added fix for MapSO co-ordinate wrapping

KSPCommunityFixes/Modding/PersistentIConfigNode.cs
If a Persistent object with IConfigNode does CreateObject/LoadObject as its way of saving and loading, and the subobjects do the same, stock throws. This fixes that by encapsulating the readlinks/writelinks (and removeAfter) to the specific pass.
=> Fix nested Persistent IConfigNode

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/KSPCommunityFixes.csproj, KSPCommunityFixes/Performance/ConfigNodePerf.cs, KSPCommunityFixes/Properties/AssemblyInfo.cs, README.md
Rewrite PreFormatConfig to iterate through strings less and to support skipping checking for {} and //
Also patch writing for a little bit of extra perf.
The preformat patch includes, disabled, siimav's parallel implementaiton; it's disabled because at the moment it's strictly slower than stock code AFAICT.
For testing, add this to a file in gamedata and then load craft/saves.
```
@KSP_COMMUNITY_FIXES:FINAL
{
@CONFIGNODE_PERF_SKIP_PROCESSING_KEYS
{
item = attPos0
}
@CONFIGNODE_PERF_SKIP_PROCESSING_SUBSTRINGS
{
item = attRot
}
}
```
Note that the skip nodes will only apply after MM loads; before that you'll just get the regular speedup.
=> Improve ConfigNode load/save perf

GameData/KSPCommunityFixes/KSPCommunityFixes.version, GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/KSPCommunityFixes.csproj, KSPCommunityFixes/Modding/ModUpgradePipeline.cs, KSPCommunityFixes/Properties/AssemblyInfo.cs, README.md
Adds a new modding patch which changes the functionality of SaveUpgradePipeline for mods. Now mods' UpgradeScripts get passed their own version in the sfs/craft file (or 0.0.0 if it predates this KSPCF version), and they can run based off their own versioning. FileVersion is used when present instead of base assembly version since most mods keep base version fixed so that they can be referenced by other mods safely, and just change fileversion.
Like the other modding patches, this defaults to off, since it is possible it will break some existing modding UpgradeScripts that haven't been rewritten to support this.
=> Mod upgrade pipeline

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/KSPCommunityFixes.csproj, KSPCommunityFixes/Modding/ModUpgradePipeline.cs, KSPCommunityFixes/Modding/PersistentIConfigNode.cs, KSPCommunityFixes/Performance/ConfigNodePerf.cs, KSPCommunityFixes/Properties/AssemblyInfo.cs, README.md
* Complete parser rewrite (again) entirely eliminating recursion. This makes the previous 'skip' methodology unnecessary since the speedup is sufficient.
* Also overrides other string-based methods in ConfigNode like the sanitize/clean methods and ToString.
* sfs and craft files skip some sanity checking on node and value strings.
* Rewrite reading and writing objects via Persistent attributes
* Allow skipping writing indents when saving ConfigNodes
* Add KSPAssembly attribute so other mods can bind (and use the rewritten ConfigNode read/write stuff, i.e. TypeCache).
=> More ConfigNode perf

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/BugFixes/RestoreMaxPhysicsDT.cs, KSPCommunityFixes/KSPCommunityFixes.csproj
When using physics warp, Unity will set the max physics dt to be at least as high as the scaled physics dt.  But KSP will never restore it back to the normal value from the settings.  This can degrade performance as it allows more FixedUpdates to run per frame.
reported by Wilds on the forum: https://forum.kerbalspaceprogram.com/index.php?/topic/184740-solved-losing-300-performance-after-time-warping/
=> Add RestoreMaxPhysicsDT

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/BugFixes/DockingPortConserveMomentum.cs, KSPCommunityFixes/KSPCommunityFixes.csproj, README.md
Averages the docking force between the two ports. This fixes the [docking port Kraken drive](https://wiki.kerbalspaceprogram.com/wiki/Docking_Port_Drive) and other unphysical behavior.
=> Make docking ports conserve momentum

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/BugFixes/PropellantFlowDescription.cs, KSPCommunityFixes/KSPCommunityFixes.csproj, README.md
Fix printing the resource's base flow mode instead of the (potentially overridden) propellant's flow mode when printing propellants in an engine's info panel in the Part Tooltip.
=> Fix Propellant's GetFlowModeDescription

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/KSPCommunityFixes.csproj, KSPCommunityFixes/QoL/BetterEditorUndoRedo.cs, README.md
See https://github.com/KSPModdingLibs/KSPCommunityFixes/issues/172
In stock, undo state is captured after part events are complete, and undoing will restore the state captured before that.
This make the user experience quite poor as undoing will loose all PAW tweaks made in between attach/detach actions.
This patch invert the undo/redo state capture logic, by moving state capture before attaching / detaching instead of after, and by capturing the current state when undoing is requested, in case a redo is requested next (see the RestoreState() patch)
Unfortunately, the crew assignement (VesselCrewManifest) is updated based on the last serialized undo state, so doing this notably result in the crew assignement window being out of sync with the ship current state. To fix this, after …
=> Better editor undo redo

KSPCommunityFixes/BugFixes/PAWGroupMemory.cs
This sort of addresses issue #50 , but as of right now we don't persist this state to disk.  This seems very similar to the intended behavior of `GameSettings.collpasedPAWGroups`, but that system can only collapse groups that the user had collapsed, not expand ones that had been manually expanded.
=> PAWGroupMemory is no longer per-window, but rather per-group

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/KSPCommunityFixes.csproj, KSPCommunityFixes/Library/Extensions.cs, KSPCommunityFixes/Performance/OptimizedModuleRaycasts.cs, README.md
Optimization of raycasts in `ModuleEngines.EngineExhaustDamage()` and `ModuleDeployableSolarPanel.CalculateTrackingLOS()` :
- Only synchronize transforms on the first raycast from any of those modules, mainly relevant when something else is moving transforms in between calls, which is often the case for active engines with gimbals, with a call time divided by 4-5 for `ModuleEngines.FixedUpdate()` when engines are actively gimballing (which is almost always the case as long as the SAS is activated)
- Cached ScaledSpace raycast results for solar panels (alongside some other smaller optimizations) : `ModuleDeployableSolarPanel.FixedUpdate()` call time is divided by between 4 (when blocked by a scaled space object) and 2 (when not blocked)
On a side note, it seems there are some unrelated …
=> Potential fix for issue #216

GameData/KSPCommunityFixes/Localization/en-us.cfg, GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/Internal/PatchSettings.cs, KSPCommunityFixes/KSPCommunityFixes.csproj, KSPCommunityFixes/QoL/OptionalMakingHistoryDLCFeatures.cs, README.md
Implement patch requested in issue #218 
Allow to disable the Making History DLC mission editor and additional launch sites features to decrease memory usage and increase loading speed. The Making History parts will still be available. Can be toggled from the KSPCF in-game settings (requires a restart), or from a MM patch (see `Settings.cfg`)
=> New QoL/Perf patch : OptionalMakingHistoryDLCFeatures

KSPCommunityFixes/QoL/BetterEditorUndoRedo.cs
We need to move calls to `EditorLogic.SetBackup()` before the actions take place (instead of after), see issue #206
The backup is created from callbacks called from the gizmo components `OnMoveEnd` / `OnRotateEnd` methods, triggered when the gizmo is released. The gizmos do have a `On*Start` method, but unfortunately they aren't hooked to a callback, and those are generic components that can potentially be used elsewhere. We can still patch those methods, and compare the gizmo instance to the `EditorLogic.gizmo*` fields.
~Requires moving the `SetBackup()` call at the beginning of the `ModulePartVariants.onVariantChanged` method~
Doesn't work because the field is already set when `ModulePartVariants.onVariantChanged`, so the changes will be saved to the backup anyway. Alternatively, we …
=> Fixes for issue #206 (BetterUndoRedo)

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/BugFixes/PartBoundsIgnoreDisabledTransforms.cs, KSPCommunityFixes/KSPCommunityFixes.csproj, README.md
Seems to be working, but I did only very limited testing.
=> Implement bugfix for #208 : PartBoundsIgnoreDisabledTransforms

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/KSPCommunityFixes.csproj, KSPCommunityFixes/Library/Collections/FastStack.cs, KSPCommunityFixes/Library/Extensions.cs, KSPCommunityFixes/Library/Numerics.cs, KSPCommunityFixes/Library/StaticHelpers.cs, KSPCommunityFixes/Performance/FastLoader.cs, KSPCommunityFixes/Performance/FlightPerf.cs
This is ongoing work to micro-optimize the various heavy duty stuff in FlightIntegrator, VesselPrecalculate and possible other flight scene low level components. The focus is on improving performance scaling in large part count situations, mainly by micro-optimizing the per-part work done in these component. 
The optimizations are meant to keep behavior as close to stock as possible, but they do introduce minor changes, and given how critical the patched methods are, any bug or behavior change is likely to have dire cascading consequences, so this will need some testing before being pushed.
As of now, there are a few other areas I want to look at before considering pushing this to a (pre)release, but I won't have much time to commit in the next weeks, not sure when I will resume working …
=> FlightIntegrator and friends micro-optimization

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/BugFixes/DragCubeLoadException.cs, KSPCommunityFixes/KSPCommunityFixes.csproj, README.md
The name field in a `DRAG_CUBE` config node is supposed to be optional. However, when the name is not included in the list of values, an `IndexOutOfRangeException` is thrown.
Even when not loaded from a config file, when the name field on a `DragCube` object is the empty string (for example, when it is default-constructed in code) it is not included in the string returned by `DragCube.SaveToString()`; this causes a problem when the `FlightIntegrator.Setup()` method uses this string to clone drag cubes.
The first instructions in `DragCube.Load(string[] data)` are:
- Check if it has the correct length (24 or 25), logging an error and returning if this is not the case
- Check if the length is 12; if it is not, take the first field as the name and skip it.
That last check should have been …
=> Fix an IndexOutOfRangeException in DragCube.Load()

KSPCommunityFixes/KSPCommunityFixes.cs, KSPCommunityFixes/KSPCommunityFixes.csproj, KSPCommunityFixes/Properties/AssemblyInfo.cs
As discussed with @JonnyOThan.
A `MonoBehaviour` gets called fairly late by MM (the ordering is explicit callbacks -> static methods -> `MonoBehaviour` methods). Furthermore, the calling order within each method signature is unspecified.
This PR inserts KSPCF as the first explicit callback, which allows other `ModuleManagerPostLoad` callbacks to rely on KSPCF fixes.
=> Always run KSPCF first in `ModuleManagerPostLoad`

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/KSPCommunityFixes.csproj, KSPCommunityFixes/Modding/KSPFieldEnumDesc.cs, README.md
Add display name and localization support for enum KSPFields. This is done by slapping the `Description` attribute to the fields. Actually KSP itself already uses this pattern in some places but mysteriously it's missing on KSPFields.
(Note: no way in hell am I writing a transpiler for this)
=> New modding patch: KSPFieldEnumDesc

KSPCommunityFixes/QoL/PAWStockGroups.cs
Add Generator PAW Group, 
a separate group per every generator
Without groups, there is no information about which generator and action the fields are related to.
=> PAWStockGroups - Generators

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/KSPCommunityFixes.csproj, KSPCommunityFixes/Performance/FasterPartFindTransform.cs, README.md
Faster, and minimal GC alloc relacements for the Part FindModelTransform* and FindHeirarchyTransform* methods.
Roughly 4 times faster on average for callers in a stock install, but this can go up to 20x faster on deep hierarchies.
The main trick is to use `Transform.Find()` instead of checking the `Transform.name` property (which will allocate a new string) for every transform in the hierarchy. There are a few quirks with `Transform.Find()` requiring additional care, but this is  overall much faster and eliminate GC allocations almost entirely.
Even though they are mostly "init-time" methods, they are used quite a bit in stock, and massively over the modding ecosystem, so this can help with loading time and scene switches : https://github.com/search?q=FindModelTransform+OR+FindModelTransfo …
=> Faster `FindModelTransform*()` and `FindHeirarchyTransform*()`

KSPCommunityFixes/BasePatch.cs, KSPCommunityFixes/KSPCommunityFixes.cs, KSPCommunityFixes/KSPCommunityFixes.csproj
Added a `[ManualPatch]` attribute.
When applied to a class derived from `BasePatch`, the patch won't be automatically applied by the default patching infrastructure.
To apply the patch, call `BasePatch.Patch()` manually. 
Note that if that call happens before ModuleManager has patched the configs (ie, before part compilation), `BasePatch.IgnoreConfig` must be overridden to return `true`, or the patch won't be applied.
Main intended usage is for patches requiring to be applied before ModuleManagerPostLoad.
=> Manual patches

KSPCommunityFixes/Performance/PartSystemsFastUpdate.cs
Address issue #194 
Complete reimplementation of `TemperatureGaugeSystem` :
- Minimal update overhead when no gauges are active/shown
- Vastly reduced update overhead when gauges/highlight are active/shown
- Gauges are now instantiated on demand, eliminating (most of) the cost on vessel load
- Gauges are now recycled when the vessel is modified / switched, instead of destroying and re-instantiating all of them immediately
Gauges were previously always instantiated for every part on the active vessel, and this was pretty slow due to triggering a lot of internal UI/layout/graphic dirtying on every gauge instantiation. Overall, the operation can take several hundred milliseconds in not-so large part count situations, leading to very significant hiccups in most vessel events involving a part …
=> Faster implementation of `TemperatureGaugeSystem`

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/KSPCommunityFixes.csproj, KSPCommunityFixes/QoL/TargetParentBody.cs, README.md
In stock KSP, you are unable to target your direct parent body, or any body that the parent body is a descendant of.  This primarily crops up when attempting to plan gravity assist chains, particularly when entering resonant orbits that will return to the initial body.  Some examples of where this can be annoying is in planning of the following assist chains starting from Kerbin:
1. Kerbin(Mun-Mun-Mun)-Kerbin(Mun)-Kerbin(Mun)-Eve
2. Kerbin-Eve-Kerbin-Kerbin-Jool
3. Kerbin-Leverage-Kerbin-Jool
In each case, it can be difficult to set up the first Kerbin flyby without first ejecting from Kerbin blind, since you cannot target Kerbin to see your future close approach.
This limitation is not a result of an inability of the targeting logic to target bodies in the parent hierarchy, but rather …
=> Allow targeting the currently orbited parent body, or any body the parent body is a descendant of

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/Performance/OptimizedModuleRaycasts.cs
See issue #301 
As a part of the `OptimizedModuleRaycasts` patch, fix `ModuleSurfaceFX.Update()` performing raycasts (and PhysX-Transform syncs) and other useless computations even when the effects have no chance of appearing. Also fix a bug with the effects not appearing at negative altitudes on ocean-less bodies.
=> Remove constant overhead from `ModuleSurfaceFX.Update()`

CHANGELOG.md, GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/BugFixes/DebugConsoleDontStealInput.cs, KSPCommunityFixes/KSPCommunityFixes.csproj, README.md
Fix the Alt+F12 console input field stealing input when a console entry is added
=> New ksp bug fix patch : DebugConsoleDontStealInput

GameData/KSPCommunityFixes/Settings.cfg, KSPCommunityFixes/BugFixes/FastAndFixedEnumExtensions.cs, KSPCommunityFixes/KSPCommunityFixes.csproj, KSPCommunityFixes/Library/Extensions.cs, KSPCommunityFixes/Modding/KSPFieldEnumDesc.cs, README.md
Fix exceptions when calling `EnumExtensions.displayDescription()` with an enum value that isn't defined, a stock bug occuring more consistently when the KSPCF KSPFieldEnumDesc patch is enabled. As part of this new FastAndFixedEnumExtensions patch, also implement a cache for the enum descriptions.
=> Fix #321 :  Fix exceptions when calling `EnumExtensions.displayDescription()`
